#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * EScript Symfony Adapter
 *
 * Translates EScript IR into Symfony-native artifacts:
 *   - config/routes.yaml
 *   - src/Controller/*.php  (with #[Route] attributes)
 *   - src/DTO/*.php         (readonly classes)
 *   - src/Service/*.php     (autowirable services)
 */

if ($argc < 2) {
    fwrite(STDERR, "Usage: php generate.php <ir-file.json> [--output=dir]\n");
    exit(1);
}

$irFile = $argv[1];
$outputDir = 'symfony-output';

for ($i = 2; $i < $argc; $i++) {
    if (str_starts_with($argv[$i], '--output=')) {
        $outputDir = substr($argv[$i], 9);
    }
}

if (!file_exists($irFile)) {
    fwrite(STDERR, "IR file not found: {$irFile}\n");
    exit(1);
}

$ir = json_decode(file_get_contents($irFile), true);
if ($ir === null) {
    fwrite(STDERR, "Invalid JSON in: {$irFile}\n");
    exit(1);
}

echo "EScript Symfony Adapter v0.1.0\n";
echo "IR source: {$ir['source']}\n";
echo str_repeat('─', 50) . "\n";

// ─── Generate config/routes.yaml ─────────────────────────────────────────────

$routes = $ir['routes'] ?? [];
if (!empty($routes)) {
    $yaml = "# Generated by EScript Symfony Adapter\n";
    $yaml .= "# Source: {$ir['source']}\n\n";

    foreach ($routes as $route) {
        $method = $route['method'];
        $path = $route['path'];
        $controller = $route['target']['controller'] ?? '';
        $action = $route['target']['action'] ?? 'index';
        $routeName = pathToRouteName($path, $action);

        $yaml .= "{$routeName}:\n";
        $yaml .= "    path: {$path}\n";
        $yaml .= "    controller: App\\Controller\\{$controller}::{$action}\n";
        $yaml .= "    methods: [{$method}]\n";
        $yaml .= "\n";
    }

    writeFile("{$outputDir}/config/routes.yaml", $yaml);
}

// ─── Generate Controllers with #[Route] attributes ──────────────────────────

$controllerGroups = [];
foreach ($routes as $route) {
    $name = $route['target']['controller'] ?? '';
    if ($name) {
        $controllerGroups[$name][] = $route;
    }
}

foreach ($controllerGroups as $controllerName => $controllerRoutes) {
    $code = "<?php\n\n";
    $code .= "declare(strict_types=1);\n\n";
    $code .= "namespace App\\Controller;\n\n";
    $code .= "use Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController;\n";
    $code .= "use Symfony\\Component\\HttpFoundation\\JsonResponse;\n";
    $code .= "use Symfony\\Component\\HttpFoundation\\Request;\n";
    $code .= "use Symfony\\Component\\Routing\\Attribute\\Route;\n";

    // Import DTOs used
    $dtoImports = [];
    foreach ($controllerRoutes as $r) {
        if (isset($r['dto'])) {
            $dtoImports[$r['dto']] = "use App\\DTO\\{$r['dto']};";
        }
    }
    foreach ($dtoImports as $import) {
        $code .= $import . "\n";
    }

    $code .= "\n";
    $code .= "class {$controllerName} extends AbstractController\n{\n";

    foreach ($controllerRoutes as $r) {
        $method = $r['method'];
        $path = $r['path'];
        $action = $r['target']['action'] ?? 'index';
        $routeName = pathToRouteName($path, $action);

        // Build #[Route] attribute
        $methods = strtoupper($method);
        $code .= "    #[Route('{$path}', name: '{$routeName}', methods: ['{$methods}'])]\n";

        // Path parameters
        $pathParams = [];
        preg_match_all('/\{(\w+)\}/', $path, $matches);
        if (!empty($matches[1])) {
            $pathParams = $matches[1];
        }

        $params = ['Request $request'];
        foreach ($pathParams as $pp) {
            $params[] = "int \${$pp}";
        }
        $paramStr = implode(', ', $params);

        $code .= "    public function {$action}({$paramStr}): JsonResponse\n";
        $code .= "    {\n";
        $code .= "        // TODO: Implement {$action}\n";
        $code .= "        return \$this->json([]);\n";
        $code .= "    }\n\n";
    }

    $code .= "}\n";

    writeFile("{$outputDir}/src/Controller/{$controllerName}.php", $code);
}

// ─── Generate DTOs as readonly classes ───────────────────────────────────────

foreach ($ir['dtos'] ?? [] as $dto) {
    $name = $dto['name'];
    $fields = $dto['fields'] ?? [];

    $code = "<?php\n\n";
    $code .= "declare(strict_types=1);\n\n";
    $code .= "namespace App\\DTO;\n\n";
    $code .= "final readonly class {$name}\n{\n";

    // Constructor with promoted properties
    if (!empty($fields)) {
        $code .= "    public function __construct(\n";
        $parts = [];
        foreach ($fields as $field) {
            $type = mapIrTypeToPhp($field['type']);
            $nullable = $field['nullable'] ?? false;
            if ($nullable) {
                $type = '?' . $type;
            }

            $prop = "        public {$type} \${$field['name']}";
            if (isset($field['default'])) {
                $prop .= ' = ' . var_export($field['default'], true);
            } elseif ($nullable) {
                $prop .= ' = null';
            }
            $parts[] = $prop;
        }
        $code .= implode(",\n", $parts) . ",\n";
        $code .= "    ) {}\n";
    }

    // toArray method
    $code .= "\n    /** @return array<string, mixed> */\n";
    $code .= "    public function toArray(): array\n";
    $code .= "    {\n";
    $code .= "        return [\n";
    foreach ($fields as $field) {
        $code .= "            '{$field['name']}' => \$this->{$field['name']},\n";
    }
    $code .= "        ];\n";
    $code .= "    }\n";

    // fromArray static factory
    $code .= "\n    /** @param array<string, mixed> \$data */\n";
    $code .= "    public static function fromArray(array \$data): self\n";
    $code .= "    {\n";
    $code .= "        return new self(\n";
    foreach ($fields as $field) {
        $default = isset($field['default']) ? var_export($field['default'], true) : 'null';
        $code .= "            {$field['name']}: \$data['{$field['name']}'] ?? {$default},\n";
    }
    $code .= "        );\n";
    $code .= "    }\n";

    $code .= "}\n";

    writeFile("{$outputDir}/src/DTO/{$name}.php", $code);
}

// ─── Generate Services ───────────────────────────────────────────────────────

foreach ($ir['services'] ?? [] as $service) {
    if (($service['tier'] ?? 'php') !== 'php') continue;

    $name = $service['name'];
    $injects = $service['injects'] ?? [];
    $methods = $service['methods'] ?? [];
    $implements = $service['implements'] ?? [];

    $code = "<?php\n\n";
    $code .= "declare(strict_types=1);\n\n";
    $code .= "namespace App\\Service;\n\n";

    $implementsStr = '';
    if (!empty($implements)) {
        $implementsStr = ' implements ' . implode(', ', $implements);
    }

    $code .= "class {$name}{$implementsStr}\n{\n";

    // Constructor with DI (Symfony autowiring)
    if (!empty($injects)) {
        $code .= "    public function __construct(\n";
        $parts = [];
        foreach ($injects as $inject) {
            $parts[] = "        private readonly {$inject['type']} \${$inject['name']}";
        }
        $code .= implode(",\n", $parts) . ",\n";
        $code .= "    ) {}\n\n";
    }

    // Methods
    foreach ($methods as $method) {
        $vis = $method['visibility'] ?? 'public';
        $params = [];
        foreach ($method['params'] ?? [] as $p) {
            $typeHint = mapIrTypeToPhp($p['type']);
            $param = "{$typeHint} \${$p['name']}";
            if (isset($p['default'])) {
                $param .= ' = ' . var_export($p['default'], true);
            }
            $params[] = $param;
        }
        $paramStr = implode(', ', $params);

        $returnType = '';
        if (isset($method['return_type'])) {
            $returnType = ': ' . mapReturnTypeToPhp($method['return_type']);
        }

        $code .= "    {$vis} function {$method['name']}({$paramStr}){$returnType}\n";
        $code .= "    {\n";
        $code .= "        // TODO: Implement {$method['name']}\n";
        $code .= "        throw new \\RuntimeException('Not implemented');\n";
        $code .= "    }\n\n";
    }

    $code .= "}\n";

    writeFile("{$outputDir}/src/Service/{$name}.php", $code);
}

echo str_repeat('─', 50) . "\n";
echo "Symfony adapter complete.\n";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function writeFile(string $path, string $content): void
{
    $dir = dirname($path);
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    file_put_contents($path, $content);
    echo "  → {$path}\n";
}

function pathToRouteName(string $path, string $action): string
{
    $clean = preg_replace('/\{[^}]+\}/', '', $path);
    $parts = array_filter(explode('/', trim($clean, '/')));
    return 'app_' . implode('_', $parts) . '_' . $action;
}

function mapIrTypeToPhp(string $type): string
{
    return match ($type) {
        'string' => 'string',
        'int' => 'int',
        'float' => 'float',
        'bool' => 'bool',
        'void' => 'void',
        default => $type,
    };
}

function mapReturnTypeToPhp(array $rt): string
{
    return match ($rt['kind'] ?? 'simple') {
        'simple' => mapIrTypeToPhp($rt['type'] ?? 'mixed'),
        'nullable' => '?' . mapIrTypeToPhp($rt['type'] ?? 'mixed'),
        'array' => 'array',
        'result' => mapIrTypeToPhp($rt['ok'] ?? 'mixed'),
        default => 'mixed',
    };
}
