#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * AI Bridge Sync — EScript ↔ Evolution Gate Synchronization Checker
 *
 * This script compares the current Evolution gate definitions against the
 * latest EScript IR to detect mismatches. It reads the sync manifest
 * generated by the EvolutionAdapter and compares it against the compiled IR.
 *
 * Usage:
 *   php ai-bridge-sync.php <ir-dir> <evolution-dir>
 *   php ai-bridge-sync.php build/ir build/evolution
 *
 * Exit codes:
 *   0 = In sync
 *   1 = Mismatch detected (CRITICAL ALERT)
 *   2 = Missing files
 */

$irDir = $argv[1] ?? 'build/ir';
$evolutionDir = $argv[2] ?? 'build/evolution';

echo "╔══════════════════════════════════════════════════╗\n";
echo "║  AI Bridge Sync — EScript ↔ Evolution           ║\n";
echo "╚══════════════════════════════════════════════════╝\n\n";

$errors = [];
$warnings = [];

// ─── Check manifest exists ───────────────────────────────────────────────────

$manifestPath = "{$evolutionDir}/.escript-sync-manifest.json";
if (!file_exists($manifestPath)) {
    fwrite(STDERR, "CRITICAL: No sync manifest found at {$manifestPath}\n");
    fwrite(STDERR, "Run the Evolution adapter first to generate it.\n");
    exit(2);
}

$manifest = json_decode(file_get_contents($manifestPath), true);
if ($manifest === null) {
    fwrite(STDERR, "CRITICAL: Invalid manifest JSON\n");
    exit(2);
}

echo "Manifest: {$manifestPath}\n";
echo "  IR version:    {$manifest['ir_version']}\n";
echo "  IR source:     {$manifest['ir_source']}\n";
echo "  Generated at:  {$manifest['generated_at']}\n";
echo "  Guards:        {$manifest['guard_count']}\n";
echo "  Routes:        {$manifest['route_count']}\n";
echo "  Services:      {$manifest['service_count']}\n";
echo str_repeat('─', 50) . "\n";

// ─── Find IR files and recompute hashes ──────────────────────────────────────

$irFiles = glob("{$irDir}/*.ir.json");
if (empty($irFiles)) {
    fwrite(STDERR, "WARNING: No IR files found in {$irDir}\n");
    $warnings[] = "No IR files found";
}

echo "\nIR files found: " . count($irFiles) . "\n";

foreach ($irFiles as $irFile) {
    $ir = json_decode(file_get_contents($irFile), true);
    if ($ir === null) {
        $errors[] = "Invalid JSON: {$irFile}";
        continue;
    }

    $currentHash = md5(json_encode($ir));
    $manifestHash = $manifest['checksums']['ir_hash'] ?? '';
    $basename = basename($irFile);

    echo "  {$basename}: hash={$currentHash}\n";

    // Check version compatibility
    $irVersion = $ir['version'] ?? '';
    $manifestVersion = $manifest['ir_version'] ?? '';

    if (!empty($irVersion) && !empty($manifestVersion)) {
        $irMajor = explode('.', $irVersion)[0];
        $manifestMajor = explode('.', $manifestVersion)[0];
        if ($irMajor !== $manifestMajor) {
            $errors[] = "MAJOR VERSION MISMATCH: IR={$irVersion} Manifest={$manifestVersion}";
        }
    }

    // Check hash drift
    if ($currentHash !== $manifestHash && $ir['source'] === $manifest['ir_source']) {
        $errors[] = "IR HASH DRIFT: {$basename} has changed since last adapter run (expected: {$manifestHash}, got: {$currentHash})";
    }

    // Check guard names match
    $irGuardNames = array_map(fn($g) => $g['name'], $ir['guards'] ?? []);
    $manifestGuardNames = $manifest['guard_names'] ?? [];

    $missingInEvolution = array_diff($irGuardNames, $manifestGuardNames);
    $extraInEvolution = array_diff($manifestGuardNames, $irGuardNames);

    if (!empty($missingInEvolution)) {
        $errors[] = "NEW GUARDS in IR not in Evolution: " . implode(', ', $missingInEvolution);
    }
    if (!empty($extraInEvolution)) {
        $warnings[] = "STALE GUARDS in Evolution not in IR: " . implode(', ', $extraInEvolution);
    }
}

// ─── Check Evolution gate files exist ────────────────────────────────────────

echo "\nEvolution gate files:\n";

$gatesConfigPath = "{$evolutionDir}/config/gates.json";
if (file_exists($gatesConfigPath)) {
    $gatesConfig = json_decode(file_get_contents($gatesConfigPath), true);
    $gateCount = count($gatesConfig['gates'] ?? []);
    echo "  config/gates.json: {$gateCount} gate(s) ✓\n";
} else {
    $errors[] = "Missing: config/gates.json";
    echo "  config/gates.json: MISSING ✗\n";
}

foreach ($manifest['guard_names'] ?? [] as $guardName) {
    $gatePath = "{$evolutionDir}/src/Gates/{$guardName}.php";
    if (file_exists($gatePath)) {
        echo "  src/Gates/{$guardName}.php ✓\n";
    } else {
        $errors[] = "Missing gate class: {$guardName}.php";
        echo "  src/Gates/{$guardName}.php MISSING ✗\n";
    }
}

// ─── Report ──────────────────────────────────────────────────────────────────

echo "\n" . str_repeat('═', 50) . "\n";

if (!empty($errors)) {
    $count = count($errors);
    echo "\n🚨 CRITICAL ALERT — {$count} issue(s) found:\n\n";
    foreach ($errors as $i => $error) {
        echo "  [{$i}] {$error}\n";
    }
    echo "\n";
    echo "ACTION REQUIRED: Re-run the Evolution adapter to synchronize:\n";
    echo "  php adapters/evolution/EvolutionAdapter.php build/ir/<file>.ir.json --output=<evolution-dir>\n\n";

    if (!empty($warnings)) {
        echo "Warnings:\n";
        foreach ($warnings as $w) {
            echo "  ⚠ {$w}\n";
        }
    }

    exit(1);
}

if (!empty($warnings)) {
    $count = count($warnings);
    echo "\n⚠ {$count} warning(s):\n";
    foreach ($warnings as $w) {
        echo "  ⚠ {$w}\n";
    }
    echo "\n";
}

echo "\n✅ IN SYNC — All Evolution gates match the current IR.\n";
echo "   Last sync: {$manifest['generated_at']}\n";
echo "   IR hash:   {$manifest['checksums']['ir_hash']}\n\n";

exit(0);
